# Project Information
site_name: PagerDuty Incident Response Documentation
site_description: これはPagerDutyのインシデント対応プロセスに関するドキュメントです。オンコールを始める新入社員のためだけではなく、重大インシデントに対する事前と事後の処理についても解説します。
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: https://ueokande.github.io/incident-response-docs-ja/

# Repository
repo_url: https://github.com/ueokande/incident-response-docs-ja/

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra_javascript: ['js/github_forks.js']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/covers/default.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Contents
pages:
  - Home: 'index.md'
  - はじめに: 'getting_started.md'
  - オンコール:
    - オンコールを始める: 'oncall/being_oncall.md'
    - 誰がオンコールになるか: 'oncall/whos_oncall.md'
    - アラートの原則: 'oncall/alerting_principles.md'
  - インシデント前に:
    - インシデントとはなにか？: 'before/what_is_an_incident.md'
    - 深刻度レベル: 'before/severity_levels.md'
    - 異なる役割: 'before/different_roles.md'
    - 通話中のエチケット: 'before/call_etiquette.md'
    - 複雑なインシデント: 'before/complex_incidents.md'
  - インシデント発生中:
    - インシデント発生中: 'during/during_an_incident.md'
    - セキュリティインシデント: 'during/security_incident_response.md'
  - インシデント収束後:
    - インシデント収束後: 'after/after_an_incident.md'
    - ポストモーテムプロセス: 'after/post_mortem_process.md'
    - ポストモーテムテンプレート: 'after/post_mortem_template.md'
    - 効果的なポストモーテム: 'after/effective_post_mortems.md'
  - トレーニング:
    - 概要: 'training/overview.md'
    - インシデントコマンダー: 'training/incident_commander.md'
    - 補佐: 'training/deputy.md'
    - 記録係: 'training/scribe.md'
    - 内容領域専門家: 'training/subject_matter_expert.md'
    - 顧客窓口: 'training/customer_liaison.md'
    - 内部窓口: 'training/internal_liaison.md'
    - 用語集: 'training/glossary.md'
  - トレーニングコース:
    - インシデント対応: 'training/courses/incident_response.md'
  - 追加資料:
    - 読み物: 'resources/reading.md'
    - ChatOps: 'resources/chatops.md'
    - アンチパターン: 'resources/anti_patterns.md'
  - このドキュメントについて: 'about.md'

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
